-- Human handoff schema (Portal Supabase project)
-- Notes:
-- 1) The feature gate `workspace_apps.human_agents_enabled` lives in Dashboard Supabase.
--    Check that in API code before using these tables.
-- 2) This schema is agent-scoped first (not workspace-scoped).

create table if not exists public.human_agents_on_shift (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  agent_id uuid not null,
  human_agent_user_id uuid not null,
  is_on_shift boolean not null default true,
  on_break boolean not null default false,
  wrap_up boolean not null default false,
  max_concurrent_chats integer null,
  last_seen_at timestamp with time zone null,
  constraint human_agents_on_shift_pkey primary key (id),
  constraint human_agents_on_shift_agent_id_fkey
    foreign key (agent_id) references public.agents (id)
    on update cascade on delete cascade,
  constraint human_agents_on_shift_human_agent_user_id_fkey
    foreign key (human_agent_user_id) references public.users (id)
    on update cascade on delete cascade,
  constraint human_agents_on_shift_max_concurrent_chats_chk
    check (
      max_concurrent_chats is null or max_concurrent_chats > 0
    )
) tablespace pg_default;

create unique index if not exists human_agents_on_shift_unique_active_agent
  on public.human_agents_on_shift using btree (agent_id, human_agent_user_id)
  where is_on_shift = true;

create index if not exists human_agents_on_shift_wrapup_idx
  on public.human_agents_on_shift using btree (
    agent_id,
    human_agent_user_id,
    is_on_shift,
    wrap_up,
    on_break,
    updated_at
  );

create table if not exists public.human_handoff_chats (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  started_at timestamp with time zone not null default now(),
  ended_at timestamp with time zone null,
  agent_id uuid not null,
  chat_source text not null,
  source text null,
  chat_id text not null,
  annon text null,
  external_user_id text null,
  country text null,
  subject text null,
  summery text null,
  shift_id bigint null,
  assigned_human_agent_user_id uuid not null,
  status text not null default 'active',
  constraint human_handoff_chats_pkey primary key (id),
  constraint human_handoff_chats_agent_id_fkey
    foreign key (agent_id) references public.agents (id)
    on update cascade on delete cascade,
  constraint human_handoff_chats_assigned_human_agent_user_id_fkey
    foreign key (assigned_human_agent_user_id) references public.users (id)
    on update cascade on delete cascade,
  constraint human_handoff_chats_shift_id_fkey
    foreign key (shift_id) references public.human_agents_on_shift (id)
    on update cascade on delete set null,
  constraint human_handoff_chats_status_chk
    check (status in ('active', 'paused', 'closed')),
  constraint human_handoff_chats_source_chk
    check (chat_source in ('widget', 'meta', 'whatsapp', 'telegram'))
) tablespace pg_default;

create unique index if not exists human_handoff_chats_unique_active_chat
  on public.human_handoff_chats using btree (agent_id, chat_source, chat_id)
  where status = 'active';

create index if not exists human_handoff_chats_assignee_idx
  on public.human_handoff_chats using btree (assigned_human_agent_user_id, status, updated_at);

create index if not exists human_handoff_chats_agent_status_idx
  on public.human_handoff_chats using btree (agent_id, status, created_at);

create index if not exists human_handoff_chats_shift_idx
  on public.human_handoff_chats using btree (shift_id);

-- Round-robin pointer to keep assignment fair and deterministic.
-- Keep one row per agent_id. The API updates this in the same transaction
-- when creating a new handoff chat.
create table if not exists public.human_handoff_assignment_state (
  agent_id uuid not null,
  last_assigned_human_agent_user_id uuid null,
  last_assigned_at timestamp with time zone null,
  updated_at timestamp with time zone not null default now(),
  constraint human_handoff_assignment_state_pkey primary key (agent_id),
  constraint human_handoff_assignment_state_agent_id_fkey
    foreign key (agent_id) references public.agents (id)
    on update cascade on delete cascade,
  constraint human_handoff_assignment_state_last_assigned_human_agent_user_id_fkey
    foreign key (last_assigned_human_agent_user_id) references public.users (id)
    on update cascade on delete set null
) tablespace pg_default;

-- Widget-safe human message stream (for realtime to unauth/public users).
create table if not exists public.widget_human_messages (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  agent_id uuid not null,
  annon text null,
  chat_id text not null,
  prompt text null,
  result text null,
  source text null default 'widget',
  human_reply boolean not null default true,
  sender_type text not null,
  assigned_human_agent_user_id uuid null,
  constraint widget_human_messages_pkey primary key (id),
  constraint widget_human_messages_agent_id_fkey
    foreign key (agent_id) references public.agents (id)
    on update cascade on delete cascade,
  constraint widget_human_messages_assigned_human_agent_user_id_fkey
    foreign key (assigned_human_agent_user_id) references public.users (id)
    on update cascade on delete set null,
  constraint widget_human_messages_sender_type_chk
    check (sender_type in ('customer', 'human_agent')),
  constraint widget_human_messages_non_empty_chk
    check (
      nullif(btrim(coalesce(prompt, '')), '') is not null
      or nullif(btrim(coalesce(result, '')), '') is not null
    )
) tablespace pg_default;

create index if not exists widget_human_messages_chat_idx
  on public.widget_human_messages using btree (agent_id, chat_id, created_at);

create index if not exists widget_human_messages_agent_created_idx
  on public.widget_human_messages using btree (agent_id, created_at);
