-- Dashboard Supabase project.
-- Stores first-touch channel attribution before a human handoff chat exists.
-- The dispatcher webhook is stateless across messages, so WhatsApp referral
-- metadata has to be persisted outside human_handoff_chats until a tool call
-- creates or updates the portal chat.

create table if not exists public.channel_chat_attribution (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  workspace_id uuid not null,
  agent_id uuid null,
  chat_source text not null,
  chat_id text not null,
  annon text null,
  ad_campaign_headline text null,
  ad_campaign_body text null,
  constraint channel_chat_attribution_pkey primary key (id),
  constraint channel_chat_attribution_workspace_id_fkey
    foreign key (workspace_id) references public.workspace (id)
    on update cascade on delete cascade,
  constraint channel_chat_attribution_agent_id_fkey
    foreign key (agent_id) references public.agents (id)
    on update cascade on delete set null,
  constraint channel_chat_attribution_source_chk
    check (chat_source in ('widget', 'meta', 'whatsapp', 'telegram')),
  constraint channel_chat_attribution_workspace_source_chat_key
    unique (workspace_id, chat_source, chat_id)
) tablespace pg_default;

create index if not exists channel_chat_attribution_workspace_idx
  on public.channel_chat_attribution using btree (workspace_id, chat_source, chat_id);

create index if not exists channel_chat_attribution_agent_idx
  on public.channel_chat_attribution using btree (agent_id, chat_source, chat_id);

-- Portal Supabase project. Safe to run even if these already exist.
alter table if exists public.human_handoff_chats
  add column if not exists ad_campaign_headline text null;

alter table if exists public.human_handoff_chats
  add column if not exists ad_campaign_body text null;
