-- Analytics table for backend cost/latency study.
-- Service key only: no RLS, and no privileges for anon/authenticated/public.

create table if not exists public.message_analytics (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),

  -- Core dimensions
  agent_id uuid null references public.agents (id) on update cascade on delete cascade,
  workspace_id uuid null references public.workspace (id) on update cascade on delete cascade,
  endpoint text not null default 'chat', -- chat | widget
  source text not null default 'api',
  country text null,

  -- Session linkage (optional, for conversation-level aggregation)
  annon text null,
  chat_id text null,

  -- Models used
  model_mini text not null default 'gpt-5-mini',
  model_nano text not null default 'gpt-5-nano',

  -- Token accounting (requested)
  mini_input_tokens bigint not null default 0,
  mini_output_tokens bigint not null default 0,
  nano_input_tokens bigint not null default 0,
  nano_output_tokens bigint not null default 0,

  -- Optional but high-value analytics fields
  action_used boolean not null default false,
  action_count integer not null default 0,
  rag_used boolean not null default false,
  rag_chunk_count integer not null default 0,
  status_code integer not null default 200,
  latency_total_ms integer null,
  latency_mini_ms integer null,
  latency_nano_ms integer null,
  latency_tools_ms integer null,
  error_code text null
);

create index if not exists message_analytics_agent_created_idx
  on public.message_analytics (agent_id, created_at desc);

create index if not exists message_analytics_workspace_created_idx
  on public.message_analytics (workspace_id, created_at desc);

create index if not exists message_analytics_endpoint_created_idx
  on public.message_analytics (endpoint, created_at desc);

-- No RLS on this table (service key access pattern).
alter table public.message_analytics disable row level security;

-- Restrict direct access from public API roles.
revoke all on table public.message_analytics from public;
revoke all on table public.message_analytics from anon;
revoke all on table public.message_analytics from authenticated;

-- Allow service role only (backend secret key path).
grant all on table public.message_analytics to service_role;
grant usage, select on sequence public.message_analytics_id_seq to service_role;
